//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tema3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material_Didactic
    {
        public int id { get; set; }
        public string path { get; set; }
        public int id_materie { get; set; }
        public int id_clasa { get; set; }
    
        public virtual Clasa Clasa { get; set; }
        public virtual Materie Materie { get; set; }
    }
}
