//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tema3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medie
    {
        public int id { get; set; }
        public int id_elev { get; set; }
        public int id_materie { get; set; }
        public int medie1 { get; set; }
        public int semestru { get; set; }
    
        public virtual Elev Elev { get; set; }
        public virtual Materie Materie { get; set; }
    }
}
