//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tema3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CatalogEntities : DbContext
    {
        public CatalogEntities()
            : base("name=CatalogEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<Absenta> Absente { get; set; }
        public virtual DbSet<Clasa> Clase { get; set; }
        public virtual DbSet<Elev> Elevi { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<Material_Didactic> Materiale_Didactice { get; set; }
        public virtual DbSet<Materie> Materii { get; set; }
        public virtual DbSet<Medie> Medii { get; set; }
        public virtual DbSet<Nota> Note { get; set; }
        public virtual DbSet<Profesor> Profesori { get; set; }
        public virtual DbSet<Profesor_Materie_Clasa> Profesori_Materii_Clase { get; set; }

        public virtual ObjectResult<AbsenteDiriginte_Result> AbsenteDiriginte(Nullable<int> idDiriginte)
        {
            var idDiriginteParameter = idDiriginte.HasValue ?
                new ObjectParameter("idDiriginte", idDiriginte) :
                new ObjectParameter("idDiriginte", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AbsenteDiriginte_Result>("AbsenteDiriginte", idDiriginteParameter);
        }
    
        public virtual ObjectResult<AbsenteProfesor_Result> AbsenteProfesor(Nullable<int> idProfesor)
        {
            var idProfesorParameter = idProfesor.HasValue ?
                new ObjectParameter("idProfesor", idProfesor) :
                new ObjectParameter("idProfesor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AbsenteProfesor_Result>("AbsenteProfesor", idProfesorParameter);
        }
    
        public virtual ObjectResult<AfisareAbsProf_Result> AfisareAbsProf(Nullable<int> idProf)
        {
            var idProfParameter = idProf.HasValue ?
                new ObjectParameter("idProf", idProf) :
                new ObjectParameter("idProf", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AfisareAbsProf_Result>("AfisareAbsProf", idProfParameter);
        }
    
        public virtual ObjectResult<AfisareEleviDirig_Result> AfisareEleviDirig(Nullable<int> idDirig)
        {
            var idDirigParameter = idDirig.HasValue ?
                new ObjectParameter("idDirig", idDirig) :
                new ObjectParameter("idDirig", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AfisareEleviDirig_Result>("AfisareEleviDirig", idDirigParameter);
        }
    
        public virtual ObjectResult<AfisareMediiDirig_Result> AfisareMediiDirig(Nullable<int> idDirig)
        {
            var idDirigParameter = idDirig.HasValue ?
                new ObjectParameter("idDirig", idDirig) :
                new ObjectParameter("idDirig", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AfisareMediiDirig_Result>("AfisareMediiDirig", idDirigParameter);
        }
    
        public virtual ObjectResult<AfisareMediiProf_Result> AfisareMediiProf(Nullable<int> idProf)
        {
            var idProfParameter = idProf.HasValue ?
                new ObjectParameter("idProf", idProf) :
                new ObjectParameter("idProf", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AfisareMediiProf_Result>("AfisareMediiProf", idProfParameter);
        }
    
        public virtual ObjectResult<CautareLogin_Result> CautareLogin(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CautareLogin_Result>("CautareLogin", usernameParameter, passwordParameter);
        }
    
        public virtual int InserareinAbsenta(Nullable<int> idElev, Nullable<int> idMat, string data, Nullable<bool> motivata, Nullable<bool> motivabila, Nullable<int> semestru)
        {
            var idElevParameter = idElev.HasValue ?
                new ObjectParameter("idElev", idElev) :
                new ObjectParameter("idElev", typeof(int));
    
            var idMatParameter = idMat.HasValue ?
                new ObjectParameter("idMat", idMat) :
                new ObjectParameter("idMat", typeof(int));
    
            var dataParameter = data != null ?
                new ObjectParameter("data", data) :
                new ObjectParameter("data", typeof(string));
    
            var motivataParameter = motivata.HasValue ?
                new ObjectParameter("motivata", motivata) :
                new ObjectParameter("motivata", typeof(bool));
    
            var motivabilaParameter = motivabila.HasValue ?
                new ObjectParameter("motivabila", motivabila) :
                new ObjectParameter("motivabila", typeof(bool));
    
            var semestruParameter = semestru.HasValue ?
                new ObjectParameter("semestru", semestru) :
                new ObjectParameter("semestru", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InserareinAbsenta", idElevParameter, idMatParameter, dataParameter, motivataParameter, motivabilaParameter, semestruParameter);
        }
    
        public virtual int InserareinClasa(string denumire, string specializare, Nullable<int> idDirig)
        {
            var denumireParameter = denumire != null ?
                new ObjectParameter("denumire", denumire) :
                new ObjectParameter("denumire", typeof(string));
    
            var specializareParameter = specializare != null ?
                new ObjectParameter("specializare", specializare) :
                new ObjectParameter("specializare", typeof(string));
    
            var idDirigParameter = idDirig.HasValue ?
                new ObjectParameter("idDirig", idDirig) :
                new ObjectParameter("idDirig", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InserareinClasa", denumireParameter, specializareParameter, idDirigParameter);
        }
    
        public virtual int InserareinElev(string nume, string prenume, Nullable<int> idCls, Nullable<int> idLog)
        {
            var numeParameter = nume != null ?
                new ObjectParameter("nume", nume) :
                new ObjectParameter("nume", typeof(string));
    
            var prenumeParameter = prenume != null ?
                new ObjectParameter("prenume", prenume) :
                new ObjectParameter("prenume", typeof(string));
    
            var idClsParameter = idCls.HasValue ?
                new ObjectParameter("idCls", idCls) :
                new ObjectParameter("idCls", typeof(int));
    
            var idLogParameter = idLog.HasValue ?
                new ObjectParameter("idLog", idLog) :
                new ObjectParameter("idLog", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InserareinElev", numeParameter, prenumeParameter, idClsParameter, idLogParameter);
        }
    
        public virtual int InserareinLogin(string usr, string prl)
        {
            var usrParameter = usr != null ?
                new ObjectParameter("usr", usr) :
                new ObjectParameter("usr", typeof(string));
    
            var prlParameter = prl != null ?
                new ObjectParameter("prl", prl) :
                new ObjectParameter("prl", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InserareinLogin", usrParameter, prlParameter);
        }
    
        public virtual int InserareinMaterie(string denumire)
        {
            var denumireParameter = denumire != null ?
                new ObjectParameter("denumire", denumire) :
                new ObjectParameter("denumire", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InserareinMaterie", denumireParameter);
        }
    
        public virtual int InserareinNota(Nullable<int> idElev, Nullable<int> idMat, Nullable<int> nota, Nullable<bool> teza, Nullable<int> sem)
        {
            var idElevParameter = idElev.HasValue ?
                new ObjectParameter("idElev", idElev) :
                new ObjectParameter("idElev", typeof(int));
    
            var idMatParameter = idMat.HasValue ?
                new ObjectParameter("idMat", idMat) :
                new ObjectParameter("idMat", typeof(int));
    
            var notaParameter = nota.HasValue ?
                new ObjectParameter("nota", nota) :
                new ObjectParameter("nota", typeof(int));
    
            var tezaParameter = teza.HasValue ?
                new ObjectParameter("teza", teza) :
                new ObjectParameter("teza", typeof(bool));
    
            var semParameter = sem.HasValue ?
                new ObjectParameter("sem", sem) :
                new ObjectParameter("sem", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InserareinNota", idElevParameter, idMatParameter, notaParameter, tezaParameter, semParameter);
        }
    
        public virtual int InserareinProfesor(string nume, string prenume, Nullable<int> idLog)
        {
            var numeParameter = nume != null ?
                new ObjectParameter("nume", nume) :
                new ObjectParameter("nume", typeof(string));
    
            var prenumeParameter = prenume != null ?
                new ObjectParameter("prenume", prenume) :
                new ObjectParameter("prenume", typeof(string));
    
            var idLogParameter = idLog.HasValue ?
                new ObjectParameter("idLog", idLog) :
                new ObjectParameter("idLog", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InserareinProfesor", numeParameter, prenumeParameter, idLogParameter);
        }
    
        public virtual int InserareinProfMatCls(Nullable<int> idProf, Nullable<int> idMat, Nullable<int> idCls, Nullable<bool> teza)
        {
            var idProfParameter = idProf.HasValue ?
                new ObjectParameter("idProf", idProf) :
                new ObjectParameter("idProf", typeof(int));
    
            var idMatParameter = idMat.HasValue ?
                new ObjectParameter("idMat", idMat) :
                new ObjectParameter("idMat", typeof(int));
    
            var idClsParameter = idCls.HasValue ?
                new ObjectParameter("idCls", idCls) :
                new ObjectParameter("idCls", typeof(int));
    
            var tezaParameter = teza.HasValue ?
                new ObjectParameter("teza", teza) :
                new ObjectParameter("teza", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InserareinProfMatCls", idProfParameter, idMatParameter, idClsParameter, tezaParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> LoginElev(Nullable<int> idLogin)
        {
            var idLoginParameter = idLogin.HasValue ?
                new ObjectParameter("idLogin", idLogin) :
                new ObjectParameter("idLogin", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("LoginElev", idLoginParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> LoginProfesor(Nullable<int> idLogin)
        {
            var idLoginParameter = idLogin.HasValue ?
                new ObjectParameter("idLogin", idLogin) :
                new ObjectParameter("idLogin", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("LoginProfesor", idLoginParameter);
        }
    
        public virtual ObjectResult<MaterialElev_Result> MaterialElev(Nullable<int> idElev)
        {
            var idElevParameter = idElev.HasValue ?
                new ObjectParameter("idElev", idElev) :
                new ObjectParameter("idElev", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MaterialElev_Result>("MaterialElev", idElevParameter);
        }
    
        public virtual ObjectResult<MaterialProfesor_Result> MaterialProfesor(Nullable<int> idProf)
        {
            var idProfParameter = idProf.HasValue ?
                new ObjectParameter("idProf", idProf) :
                new ObjectParameter("idProf", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MaterialProfesor_Result>("MaterialProfesor", idProfParameter);
        }
    
        public virtual ObjectResult<string> MateriiElev(Nullable<int> idElev)
        {
            var idElevParameter = idElev.HasValue ?
                new ObjectParameter("idElev", idElev) :
                new ObjectParameter("idElev", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("MateriiElev", idElevParameter);
        }
    
        public virtual int ModificareClasa(Nullable<int> id, string denumire, string specializare, Nullable<int> idDirig)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var denumireParameter = denumire != null ?
                new ObjectParameter("denumire", denumire) :
                new ObjectParameter("denumire", typeof(string));
    
            var specializareParameter = specializare != null ?
                new ObjectParameter("specializare", specializare) :
                new ObjectParameter("specializare", typeof(string));
    
            var idDirigParameter = idDirig.HasValue ?
                new ObjectParameter("idDirig", idDirig) :
                new ObjectParameter("idDirig", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ModificareClasa", idParameter, denumireParameter, specializareParameter, idDirigParameter);
        }
    
        public virtual int ModificareElev(Nullable<int> id, string nume, string prenume, Nullable<int> idClasa, Nullable<int> idLogin)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var numeParameter = nume != null ?
                new ObjectParameter("nume", nume) :
                new ObjectParameter("nume", typeof(string));
    
            var prenumeParameter = prenume != null ?
                new ObjectParameter("prenume", prenume) :
                new ObjectParameter("prenume", typeof(string));
    
            var idClasaParameter = idClasa.HasValue ?
                new ObjectParameter("idClasa", idClasa) :
                new ObjectParameter("idClasa", typeof(int));
    
            var idLoginParameter = idLogin.HasValue ?
                new ObjectParameter("idLogin", idLogin) :
                new ObjectParameter("idLogin", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ModificareElev", idParameter, numeParameter, prenumeParameter, idClasaParameter, idLoginParameter);
        }
    
        public virtual int ModificareLogin(Nullable<int> id, string user, string parola)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            var parolaParameter = parola != null ?
                new ObjectParameter("parola", parola) :
                new ObjectParameter("parola", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ModificareLogin", idParameter, userParameter, parolaParameter);
        }
    
        public virtual int ModificareMaterie(Nullable<int> id, string denumire)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var denumireParameter = denumire != null ?
                new ObjectParameter("denumire", denumire) :
                new ObjectParameter("denumire", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ModificareMaterie", idParameter, denumireParameter);
        }
    
        public virtual int ModificarePMC(Nullable<int> id, Nullable<int> idProfesor, Nullable<int> idMaterie, Nullable<int> idClasa, Nullable<bool> teza)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var idProfesorParameter = idProfesor.HasValue ?
                new ObjectParameter("idProfesor", idProfesor) :
                new ObjectParameter("idProfesor", typeof(int));
    
            var idMaterieParameter = idMaterie.HasValue ?
                new ObjectParameter("idMaterie", idMaterie) :
                new ObjectParameter("idMaterie", typeof(int));
    
            var idClasaParameter = idClasa.HasValue ?
                new ObjectParameter("idClasa", idClasa) :
                new ObjectParameter("idClasa", typeof(int));
    
            var tezaParameter = teza.HasValue ?
                new ObjectParameter("teza", teza) :
                new ObjectParameter("teza", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ModificarePMC", idParameter, idProfesorParameter, idMaterieParameter, idClasaParameter, tezaParameter);
        }
    
        public virtual int ModificareProfesor(Nullable<int> id, string nume, string prenume, Nullable<int> idLogin)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var numeParameter = nume != null ?
                new ObjectParameter("nume", nume) :
                new ObjectParameter("nume", typeof(string));
    
            var prenumeParameter = prenume != null ?
                new ObjectParameter("prenume", prenume) :
                new ObjectParameter("prenume", typeof(string));
    
            var idLoginParameter = idLogin.HasValue ?
                new ObjectParameter("idLogin", idLogin) :
                new ObjectParameter("idLogin", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ModificareProfesor", idParameter, numeParameter, prenumeParameter, idLoginParameter);
        }
    
        public virtual int MotivareAbsenta(Nullable<int> id, Nullable<bool> motivata)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var motivataParameter = motivata.HasValue ?
                new ObjectParameter("motivata", motivata) :
                new ObjectParameter("motivata", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MotivareAbsenta", idParameter, motivataParameter);
        }
    
        public virtual ObjectResult<NoteMedie_Result> NoteMedie(Nullable<int> idElev, Nullable<int> idMaterie)
        {
            var idElevParameter = idElev.HasValue ?
                new ObjectParameter("idElev", idElev) :
                new ObjectParameter("idElev", typeof(int));
    
            var idMaterieParameter = idMaterie.HasValue ?
                new ObjectParameter("idMaterie", idMaterie) :
                new ObjectParameter("idMaterie", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NoteMedie_Result>("NoteMedie", idElevParameter, idMaterieParameter);
        }
    
        public virtual ObjectResult<NoteProfesor_Result> NoteProfesor(Nullable<int> idProfesor)
        {
            var idProfesorParameter = idProfesor.HasValue ?
                new ObjectParameter("idProfesor", idProfesor) :
                new ObjectParameter("idProfesor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NoteProfesor_Result>("NoteProfesor", idProfesorParameter);
        }
    
        public virtual int StergereClasa(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("StergereClasa", idParameter);
        }
    
        public virtual int StergereElev(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("StergereElev", idParameter);
        }
    
        public virtual int StergereLogin(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("StergereLogin", idParameter);
        }
    
        public virtual int StergereMaterie(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("StergereMaterie", idParameter);
        }
    
        public virtual int StergereNota(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("StergereNota", idParameter);
        }
    
        public virtual int StergerePMC(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("StergerePMC", idParameter);
        }
    
        public virtual int StergereProfesor(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("StergereProfesor", idParameter);
        }
    }
}
